### ISSUE TITLE
[Crash]: When using Optifine

### ISSUE THREAD

**Issue by anomyq** [Fuzss/cutthrough#1]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.18.2

### Mod Version(s) (Required)

v3.0.0

### Minimal Setup

No

### Notes (Required)

The game crashes on startup when using "OptiFine HD U H9". I'm using a m1 macOS Monterey 12.4.

### Crash Report (Required)

no crash report

### latest.log (Optional)

https://gist.github.com/anomyq/0f96124adcc7f7e8e35e450cb599d1ff

**Comment by Fuzss** [comment]
Thanks for reporting, OptiFine is not supported unfortunately.
