### ISSUE TITLE
[Bug]: Strange interaction with fences.

### ISSUE THREAD

**Issue by Nitess** [Fuzss/cutthrough#2]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.1

### Minimal Setup (Required)

Yes

### Notes (Required)

Strange interaction with fences. The mod does not allow you to place anything (for example, a fence, torch, lantern) on the fence in direct line of sight. Sometimes it allows you to install something while jumping, and sometimes you can install something at the level of the fence, but with an incomprehensible distance limitation.

### latest.log (Required)

-

**Comment by Fuzss** [comment]
Fixed in latest version.

Thanks for all the testing you've been doing! Really helps a lot with getting those minor issues ironed out with these newer mods.
